---
title: "restingstate"
output: html_document
date: "2023-05-03"
---

```{r setup, include=FALSE}
library(tidyverse)


rawData <- read.csv(file = "restingstate_data.csv", header = TRUE)

data <- rawData %>% 
  filter(!is.na(pre_pair1)) %>%
  mutate(diff_pair1 = post_pair1 - pre_pair1,
         diff_pair3 = post_pair3 - pre_pair3,
         diff_pair4 = post_pair4 - pre_pair4,
         diff_target = post.target - Pre.target,
         diff_control = post.control - pre.control)
data$pre_date <- lubridate::mdy(data$pre_date)
data$post_date <- lubridate::mdy(data$post_date)
data <- data %>% mutate(diff_date = difftime(post_date, pre_date, units = "days"))

```


correlations between the three pairs--it looks like pair 1 is best with r = .71
```{r}
cor_target_pair1 <- cor(data$diff_target, data$diff_pair1, method = "pearson")
cor_target_pair3 <- cor(data$diff_target, data$diff_pair3, method = "pearson")
cor_target_pair4 <- cor(data$diff_target, data$diff_pair4, method = "pearson")

cor_target_pair1
cor_target_pair3
cor_target_pair4
```

then just looking at pair 1, we can run a simple linear regression--we see that this is signficant with p = 0.0141
```{r}
reg_target_pair1 <- lm(diff_target ~ diff_pair1, data = data)
summary(reg_target_pair1)
```


michelle wanted to control for time between decoder/post, so here--is still significant with p = 
```{r}
reg_target_pair1_timecontrolled <- lm(diff_target ~ diff_pair1 + diff_date, data = data)
summary(reg_target_pair1_timecontrolled)
```
